# Chapter 1: Introduction

Household surveys are the primary tool through which international development goals are monitored, and policy questions are informed based on empirical research. Accurate agricultural data are predicated on careful survey design and data collection, though practices for survey design and implementation of data collection exercises vary considerably across national statistical offices (NSOs), international organizations that generate international data public goods, NGOs, and researchers. While the importance of agricultural statistics is widely acknowledged as essential to evidence-based policymaking, tracking progress in the agricultural sector, and conducting innovative research, best practices in data collection and the research foundations of these recommendations are often ambiguous. Data collection methods may not be completely generalizable and need to be adapted to the local context, but the lessons learned across contexts and the lessons that we can generalize, can be available to the community of researchers and practitioners who collect and use agricultural data. It is the purpose of this volume to aggregate innovations in agricultural survey design from the experience of the Living Standards Measurement Study - Integrated Surveys on Agriculture (LSMS-ISA), academia, and other survey operations to provide recommendations for researchers, survey practitioners and policy analysts on lessons learned in survey design, while also highlighting topics for which more research is required to provide a conclusive survey design recommendation. From these agricultural survey design 'lessons learned', we highlight tradeoffs between household survey design choices, measurement error and data use.

In their synthesis of household survey practices, Grosh and Glewwe (2000) outlined lessons learned from 15 years of the World Bank's Living Standards Measurement Study (LSMS) surveys. The genesis of this investment in the design and implementation of household surveys was motivated by the realization that progress towards reducing poverty could only be achieved if the goal could be measured, along with determinants of poverty to facilitate policy analysis by NSOs and relevant national ministries and policymakers. Concurrently, an academic interest in understanding household consumption in low- and middle-income countries led to research foundations for measuring household consumption aggregates (Deaton and Zaidi, 2002) and the canonization of the agricultural household model (Singh et al., 1986) as the relevant unit of observation for understanding smallholder production and consumption decisions. These insights provided a basis for survey design for multi-topic household surveys focusing on linkages between productivity changes (human capital, labor productivity and later agricultural productivity) and welfare which are essential to policy analysis. A focus on household production also facilitates supply and demand comparisons for food security and agriculture sector analysis.

Out of the lessons of the past 18 years since the Grosh and Glewwe volumes, innovations in methods and measurement have improved our understanding of best practices in multi-topic household survey design. A widely noted limitation of the previous volumes and multi-topic household surveys generally has been agricultural module recommendations. Though acknowledged as a focal livelihood practice of the world's poor, multi-topic household surveys designed to measure poverty have often been limited by cursory agricultural data in part due to the burden of measuring consumption aggregates.

Rozelle (1991) described three differing approaches to agricultural survey design including a production function approach, an income statement approach and a balance sheet approach. A production function approach places emphasis on capturing how inputs create outputs for an agricultural household unit with an aim to potentially estimate the returns to different inputs on farm productivity. An income statement approach measures farm revenues and expenses with an objective of measuring farm profits. A balance sheet approach is related to the income statement approach but differs in valuing farm assets and liabilities as well as the sources of all inputs and outputs. Agricultural sector specific surveys often take alternative approaches to using the farm or area sampling as the unit of analysis rather than the household (Benedetti et al., 2010).

A recent innovation in survey design has been the LSMS-Integrated Surveys on Agriculture which have redesigned agricultural modules by recognizing first, that the unit of observation for agricultural production is often not the household, but the plot that may be managed by differing household members, and second, that improved agricultural statistics may be collected and respondent survey burden reduced by timing agricultural data collection to the agricultural production seasons in a post-planting and post-harvest questionnaire. Multiple time periods facilitate agricultural input and production recall, while also lowering the per interview time for a multi-topic household questionnaire. Repeated survey visits open the possibility of different panel types where the unit of analysis could be either the household, plot or farmer. The LSMS-ISA surveys track households and plot managers over time, but not plots due to high plot visit costs and challenges related to plot recall over time.

Improved agricultural data opens a wide range of policy analysis for both research and policy. NSOs are common implementers of agricultural surveys and require high quality agricultural data to meet a number of national policy objectives, including annual or seasonal estimation of crop production and monitoring change in agricultural production over time. Agricultural surveys, if carefully designed, can meet these objectives while also enabling additional research on the drivers of agricultural production and productivity, for example, which can inform policies aimed at improving agricultural production and rural livelihoods.

This volume is organized to assess innovations in agricultural survey design, provide practical recommendations on the design and tradeoffs inherent in agricultural survey modules, and lastly to provide lessons learned on the organization of fieldwork and the linkage of agricultural household data to other data sources. In the next chapter, Chapter 2, we assess recent methodological research conducted by the LSMS team and the academic community to inform current best practice recommendations. We discuss topics including questionnaire design, respondent selection, units of analysis, timing of data collection to understand seasonality, recall periods, and innovations in the measurement of production, land, and agricultural labor.

In Chapter 3, we discuss the design of agricultural production modules, particularly as they relate to the organization, unit of analysis, and differences in production modules by agricultural system (field crops, root crops, and agro-forestry). A key innovation in the design of agricultural surveys, which is discussed in Chapter 3, is the enumeration of land holdings of the household by agricultural plot and plot manager. This survey design choice improves the measurement and analysis of agricultural yields and generates sex-disaggregated agricultural data but creates survey design tradeoffs in the respondent's ability to recall allocation of inputs to plots which may be purchased in bulk to distribute across plots (fertilizer) or be difficult to retrospectively recall (household labor hours or days per plot).

Chapter 4 addresses the design of modules to measure agricultural factors of production given plot-level reporting including labor, capital, inputs (fertilizer and seed), and water management. Chapter 5 covers livestock production for which previous multi-topic survey design attention has been limited. As low- and middle-income countries' economies have grown, animal-based sources of food production independent of cereal and tree crop production are increasingly important. Motivation for measuring livestock or animal holdings in previous multi-topic surveys has often focused on livestock as an asset stock, yet pastoralists rely on animal rearing not only as a stock of wealth, but also as a flow of income. Measuring revenues and costs from animal production has been challenging given the frequent and often small costs associated with animal rearing and the imperfectly measured effort and time that are often important determinants of animal health and quality.

In Chapter 6, we provide practical guidance for the collection of agricultural data in a multi-topic household survey including field work logistics, some perspectives of implementers including NSOs, NGOs, and researchers. To conclude, we summarize key lessons learned and highlight future methodological research which may be promising to advance agricultural survey design methodology in Chapter 7. In the Appendices, we provide a reference questionnaire, which we use as a basis for discussing agricultural survey design choices throughout this volume.

