# Chapter 5: Livestock

Pastoral households rely on livestock assets and revenue, but livestock are also central to rural and urban households in LMICs. While livestock is a vital component of the agricultural sector, data on livestock, costs of production (veterinary services, labor, feed, and shelter costs), income sources, mortality and livestock sales are often limited in nationally representative data. Livestock modules are increasingly integrated into agricultural surveys to capture the multiple sources of livestock use. In this chapter, we cover questionnaire design choices in livestock modules highlighting measurement and empirical reasons for attention to measurement error. Livestock measurement challenges relate to capturing the reproductive and production cycles of livestock systems, noting that the salience of different farmer choices and continuous nature of production create recall challenges in the context of annual multi-topic household surveys. Detailed livestock data require attention to both the stock and flow variables in such a production system. Anagol et al. (2017) note in the context of India that median returns for cows were -7 percent with a 17 percent median return for buffalos when they assumed household labor was valued at zero. Despite mixed median returns, 51 percent and 45 percent of cow and buffalo owners reported negative returns. Measurement error may explain, in part, high fractions of negative returns, underscoring the survey design challenges of livestock measurement in household surveys. An LSMS guidebook on the livestock modules provides a more detailed review including variations in short, standard, and extended questionnaire modules (Zezza et al., 2016b).

## Measuring Stocks

A primary objective of livestock modules is to register the number of animals that are owned by a household. Description of the animal breeds, age, and sex are important characteristics to quantify the household's livestock portfolio. With the information on animal breeds and counts, livestock indices such as tropical livestock units may be constructed to compare herds across households (FAO, 2011). It is important to note that the unit of analysis for most livestock modules in multi-topic household surveys is the household herd. Ownership of livestock as with land modules has congruent measurement issues related to ownership and management of animals. As with land modules, the livestock owner may not actually be the same person who manages the livestock. This presents a potential opportunity for sex-disaggregated analysis, linking to other sections of the multi-topic household questionnaire to infer effects on welfare if the owner and livestock manager reside in the same household.

In many pastoralist communities, sedentary households may own livestock that are managed by a nomadic herder or a local herder who manages several herds for households in a village. This raises multiple measurement issues. First, the characteristics of the livestock manager may not be available for analysis because the manager does not reside in the household and is not listed as part of the household roster. Second, the manager may derive compensation from animal products such as the milk of the animals. In a production function approach, revenues from animal sourced products should be listed as revenues from the livestock and payment in-kind to managers should be listed as a cost of production to the owners. In principle, an economic definition of pastoral income would also include the net livestock value change, but in the context of multi-topic household surveys and due to the challenges of valuing livestock value changes, we compare revenues and consumption to costs related to the 'flow' variables rather than changes in the value of the animal stock. If animals are herded remotely, then the unobservability of the use of animal products creates measurement issues. Third, changes in animal stocks such as births, deaths or theft may also not be observable to the owner until herds are brought closer to the sedentary household villages which usually occurs seasonally.

## Costs of Production 

As in much agricultural survey design, a production function approach to questionnaire design requires agricultural outputs to relate to inputs. Measuring livestock inputs and the costs of livestock rearing are difficult for many of the same reasons that seasonal crop input measurement is challenging. Some costs of livestock production are seasonal and many are irregular and involve high upfront costs. This is particularly true of veterinary costs which also illustrate how the unit of analysis can matter in survey design. From a veterinary perspective, immunizations and animal care costs relate to a specific animal's health and are critical for different animals at different ages. In livestock modules collected for multi-topic household surveys, a household's herd is recorded and disaggregated by animal breed rather than at the animal level. Veterinary services may be recorded either generally for the herd or by breed. In practice, reporting veterinary services is often difficult for farmers due to longer recall periods and the often specificity of veterinary services required of individual animals rather than for an entire herd or breed. This has empirical implications on whether an analyst can estimate a herd production function or a livestock specific production function. Empirical objectives to measure either herd or livestock-specific production functions need to be balanced against whether it is realistic for farmers to provide the necessary detail for livestock inputs and outputs at the chosen unit of analysis. Other costs of production such as food costs are critical to understanding the return to livestock, but many rural animals may graze freely while other animals such as chickens or pigs may be confined to pens for their safety. In principle, the consumption of grazing lands by the herd should be valued, but this analysis would require a land-based sampling frame rather than a population-based sampling frame as in household surveys.

The cost of labor devoted to animal care and herding is also critical to understanding the costs of livestock production. Common issues with labor measurement, reviewed in the earlier chapter, apply to livestock as well. Time use is difficult to measure, particularly over recall periods longer than seven days as is attribution of labor time to certain animals.

For domestic animal production such as chickens, goats, or pigs, labor time devoted to animals may be interspersed in the households' daily activities. that includes production of household public goods. Chores such as feeding, care and minor animal enclosure maintenance would be considered as part of the household's labor market activities, while activities related to producing household public goods such as household cleaning or cooking would be considered domestic activities, not included in the labor market. Due to the interconnection of activities related to household activities and domestic animal care, women's role in livestock production may be undervalued in household surveys.

Children's work in livestock production both in terms of herding and domestic production is likely under-reported in agricultural surveys, though children play key roles in the livestock sector (FAO, 2013). While some of children's activities in the livestock sector may build their human capital, it may be considered child labor if the work includes hazardous activities or interferes with their formal education. Formal measurement of children's activities in livestock may be difficult in household-based surveys if child herders are not listed in the household roster or excluded due to household definitions that require minimum residency.

## Income sources

The challenge of measuring revenue flows from stock variables requires carefully enumerating the multiple sources of revenue. For livestock, revenue flows from the sale of milk, eggs, animal traction and dung are all potential sources of revenue. Each is challenging as milk and egg production is irregular while demand for animal traction and dung are seasonal. The survey experiment on measuring milk off-take by Zezza et al. (2016a), notes that imputing milk off-take is difficult because lactating females can be milked multiple times during the day, milking frequency varies seasonally, milk production varies by lactation stage, and reproductive and lactating females may not be milked. Milk production questions are often asked in a household survey by first soliciting the number of production months in the last twelve months and then the average production per month during production months. In addition to production-related measurement issues, valuing milk production without milk sales information requires analysts to make assumptions about sale frequency and milk prices which may vary daily or weekly depending on the milk market. In the Zezza et al. (2016a) survey experiment, they find that 12-month recall using the standard two-part household survey questions recorded similar production quantities relative to estimating a lactation curve which asks extended questions related to milk off-take at four different time periods during the annual recall period in an attempt to capture lactation dynamics. Apart from this study, there are few survey experiments to inform the design of livestock modules in agricultural surveys. Despite measurement issues in milk sales, estimates are used to inform important economic questions as in Casaburi and Macchiavello (2019) who use contract design experiments in milk sales markets to estimate time preferences for Kenyan dairy farmers and Hoddinott et al. (2015) who find a positive correlation in estimating the effects of cow ownership on children's milk consumption and stunting.

Seasonal sources of animal products such as animal traction or dung can be captured in agricultural surveys if surveys are implemented during periods of high demand for such animal products. In practice, animal traction services may be easier to value in active agricultural services markets, most likely in contexts with contract or irrigated agricultural schemes. Fully capturing dung sales is difficult as larger animals are often encouraged to freely roam in rural contexts to help fertilize the fields and eat crop residues, clearing fields for farmers. As this reciprocal arrangement between farmers and animal owners is beneficial for both parties, formal dung markets are rarer in rural contexts. Livestock holdings also serve to provide insurance against risk by providing non-crop sources of revenue from milk, egg or animal sales. Increased livestock holdings can improve food security through income diversification, but also providing a savings mechanism for rural households without access to formal financial services.

## Challenges to Livestock Measurement

While Pica-Ciamarra et al. (2014) and Zezza et al. (2016b) review best practices in livestock module design, outstanding design issues are well documented in the survey design literature and remain challenges for agricultural survey design. Many of these challenges relate to the household unit of analysis at which livestock data are collected. First, mortality and livestock sales are often under-reported in household surveys as rural households often maintain herds outside of their residence. Mortality may be under-reported if stigma is associated with animal loss or animal owners are particularly sensitive to difficult questions related to the death of animals. Livestock sales may not be frequent occurrences, so multiple sales and at which prices may be difficult for respondents to recall. Second, as noted above, many livestock sector outcomes should be recorded at the herd level rather than the household level, particularly for nomadic populations. Household surveys with a population-based sampling will never capture herd level outcomes for which area-based sampling measures may be a better unit of analysis. Lastly, FAO (2011) which outlines guidelines for preparing livestock sector reviews underscores environmental and animal welfare issues that are often outside the scope of standard household livestock modules designed to measure a herd production function. If environmental consequences or social issues related to animal herding are the objective of empirical analysis, area-based sampling may more accurately capture a representative sample of landscapes for which environmental consequences or conflict between pastoralists and farmers occur. Animal health and welfare are also not easily addressed when animal information is only captured at the animal breed level. Veterinary service expenditures may be capturing farmers engaged actively to help sick animals as opposed to evidence of animal welfare concerns.

[]{#_Toc70494955 .anchor}Table . Design Decisions in Livestock Production Measurement

+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ***Livestock Questionnaire***                                        |                                                                                                                               |                                                                                                                                                                                                                              |
+======================================================================+===============================================================================================================================+==============================================================================================================================================================================================================================+
| **LS SECTION A: Livestock Ownership**                                | Livestock breed as unit of observation and disaggregated by sex and age                                                       | Critical for accurate capture of herd size and composition information.\                                                                                                                                                     |
|                                                                      |                                                                                                                               | Valuation of livestock differs by gender and age.                                                                                                                                                                            |
|                                                                      |                                                                                                                               |                                                                                                                                                                                                                              |
|                                                                      |                                                                                                                               | Greater aggregation would place burden on respondent to sum up various different breed.                                                                                                                                      |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                      | Differentiation between local/indigenous vs improved/exotic breeds                                                            | Breed type has implication for valuation of livestock                                                                                                                                                                        |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                      | Respondent recommended to be recorded at the livestock group (large ruminants, small ruminants, poultry etc.) level           | Management responsibilities likely vary by groups of livestock and so the most informed household member may also vary at that level                                                                                         |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                      | Household member-level livestock ownership and management responsibility recorded                                             | Recording who in the household owns livestock in key to understanding gender dynamics and gaps in asset ownership; additionally, ownership is differentiated from management, which is also likely to have a gender gradient |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **LS SECTION B1: Changes in Stock over the Past 12 Months**          | Recall period for small and large ruminants: 12 months                                                                        | Events related to large and small ruminants are likely not highly frequent, e.g. gestation periods for large ruminants is 250-300 days and 140-160 days for small ruminants, making longer recall period best suited.        |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **LS SECTION B2: Changes in Stock over the Past 3 Months: Poultry**  | Recall period for poultry: 3 months                                                                                           | Events related to poultry are more frequent, e.g. gestation periods are only a few weeks, and there is limited seasonality, so that a shorter recall period is better suited.                                                |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **LS SECTION C: Breeding, Housing, Water, Feeding, and Hired Labor** | Unit of observation is livestock group (large ruminant, small ruminants, poultry, etc.)                                       | Management usually differs only between livestock groups (large ruminants, small ruminants, poultry etc.) but not between breed of the same group                                                                            |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                      | Recording of individual-level management responsibilities for different aspects of husbandry (breeding, water, housing, etc.) | Important for gender analysis                                                                                                                                                                                                |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **LS SECTION D: Animal Health**                                      | Unit of observation is livestock group (large ruminant, small ruminants, poultry, etc.)                                       | Health-related practices usually differ only between livestock groups (large ruminants, small ruminants, poultry etc.) but not between breed of the same group                                                               |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **LS SECTION E: Milk Production (Off-take)**                         | Recall period 12 months                                                                                                       | Events related to large and small ruminants are likely not highly frequent, e.g. gestation periods for large ruminants is 250-300 days and 140-160 days for small ruminants, making longer recall period best suited         |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **LS SECTION F: Egg Production**                                     | Recall period 3 months                                                                                                        | Clutching period is usually a few weeks and seasonality limited so that shorter recall period better suited                                                                                                                  |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **LS SECTION G: Animal Power**                                       | Unit of observation is livestock group (large ruminant, small ruminants, poultry, etc.)                                       | Limited variation between breeds within groups (large ruminants, small ruminants, poultry etc.).                                                                                                                             |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **LS SECTION H: Dung**                                               | Unit of observation is livestock group (large ruminant, small ruminants, poultry, etc.)                                       | Limited variation between breeds within groups (large ruminants, small ruminants, poultry etc.).                                                                                                                             |
+----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Livestock Data: Design Features of the Reference Questionnaires

The reference livestock questionnaire, which is sourced from Zezza et al. (2016b), is found in Appendix II which also indicates a shorter base set of questions which are highlighted in green. For surveys which require comprehensive data on livestock activities, the full questionnaire covers livestock ownership; changes in stocks (using a 12-month-reference period for livestock and a three-month reference period for poultry), breeding, housing water, feeding and hired labor; animal health; milk production; egg production; animal power; and dung. The questionnaire modules, or *sections* as they are referred to in Zezza et al (2016b), and the related design decisions are summarized in Table 6.

The livestock ownership section of the questionnaire establishes which animals are owned by the household, the number of owned animals, who within the household owns or manages the animals, and the main reasons for holding animals. A key survey design choice is whether to limit questions to animal types and numbers within the household or to disaggregate livestock ownership and management responsibilities by person ID within the household. Disaggregated livestock ownership and management questions permit analysis by sex, age and other individual characteristics and by animal sourced revenues.

Sections B1 and B2 of the questionnaire classify the sources for changes in the stock of large and medium-sized animals over a 12-month reference period and changes in the stock of poultry over a three-month reference period. Differences in reference periods reflect assumptions concerning the reproductive cycles of animals, the liquidity of animal markets where smaller animals may be exchanged more frequently or more likely to have differential survival rates. Both modules pose questions related to the birth, purchase, gifting of animals (both those received and given), lost, sold or slaughtered.

Animal care practices are covered in Section C of the animal questionnaire. Animal care includes breeding practices, housing, watering, feed and hired animal care labor. Recording animal care practices documents investments in animal quality, but also provides associated cost information which are essential in estimating an animal profit function or the returns to livestock investment. Section D records animal health information specific to disease, curative care, and preventive practices such as vaccination. This subsection records disease incidence as well as costs associated with vaccines and treatment.

Sections E and F record animal-sourced revenues from milk and egg production. Milk production is recorded by animal where the average number of animals milked per month and the average amount of milk produced per day. It is possible to record the person ID of the household member responsible for milking and recommended to record the average amount and earnings from weekly milk sold. The egg production module follows a similar structure with deviations in the reference period. The eggs per clutching period, the number of eggs sold and earnings over the past three months are recorded for poultry.

Sections G and H record in-kind animal uses which increase agricultural productivity via animal power and dung production. Animal power is recorded related to both transportation and agricultural production. Earnings from animal services is recorded over the past 12 months. Animal dung uses are recorded for owned animals over the past 12 months as well. Animal dung uses include manure, fuel, construction material, feed to other animals, and sales. Any dung sales are recorded in local currency over the past 12 months.

