# Appendix III: Glossary {-}

  **Term**                                         **Description**
  ------------------------------------------------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Administrative data                               Data generated as a by-product of registration and other administrative and service delivery functions of government entities or other organizations. Examples include registries of large farms or information collected through agricultural extension services.
  Agricultural season                               Agricultural season refers to the portion of a year in which seasonal crops are typically grown in a given locale. This is dictated by local climatic conditions. In agricultural survey instruments, the 'reference agricultural season' is used to demarcate and refer to the production cycle of interest.
  Agro-forestry                                     Land use system in which trees or shrubs are deliberately grown on a plot of land together with crops and animals.
  Area sampling                                    Sampling method used when no complete sampling frame is available, based on dividing the land area under study into smaller areas and sampling from the list of those smaller areas.
  Attrition                                         In longitudinal surveys, attrition refers to the loss of survey participants (households, holdings, individuals) over time, with each subsequent round of the survey.
  Bias                                              In statistics, an estimator is biased when its expected value differs from the true value of the underlying parameter.
  Census                                            The full enumeration or count of an entire population of interest, such as farms or agricultural holdings (agricultural census) or households (population and housing census).
  Compass and rope                                  A method to measure the area of a unit of land reliably using poles, robes, compasses.
  Computer Assisted Personal Interviewing (CAPI)   A survey mode in which the survey questionnaire is pre-programmed on a tablet or computer and administered to the respondent in person by an interviewer.
  Consumption aggregate                            Total value of items consumed by the household over a given reference period, common welfare metric used widely to determine whether a household is considered poor.
  Crop cutting                                     Crop cutting is a more objective measurement method for crop production than farmer recall, considered the gold standard for measuring crop production and yields. Randomly located subplots within a given plots are harvested and weighted before and after drying.
  Crop rotation                                    Farming method whereby crops on a plot are grown one after the other with the aim of maintaining fertile soil on the plot.
  Crop Yield                                       Quantity of crop obtained per unit of land area used.
  Data collection mode                              Data collection mode or survey mode is the method used to collect the data. Examples include face-to-face, telephone, mail, and web-based surveys.
  Enumerator                                       Interviewer in surveys.
  External validity                                 Extent to which results from a study or experiment can be generalized beyond its original context.
  Geospatial data                                  Data related by geographic location, such as maps, satellite or remote sensing data.
  Gold standard                                     In survey design, a method for collecting data on a given parameter that is regarded as yielding highly reliable data.
  Head of the household                             Individual household member who is (considered by other household members) the main decision maker in a given household.
  Holding                                          Economic unit of agricultural production under single management, comprising all livestock kept and all land used wholly or partly for agricultural production purposes, without regard to title, legal form, or size (FAO, WCA 2020).
  Household                                        A household usually refers to a group of individuals who eat meals together and live in the same dwelling. In addition, according to the production-based definition of the household, it consists of adult individuals co-mingle revenues from agricultural production and non-farm enterprise for consumption. The production-based definition is used less frequently.
  Household member                                  Individual who is a member of a given household.
  Intercropping                                    Cultivation of more than one temporary and/or permanent crop simultaneously on the same plot.
  Internal validity                                 Extent to which a causal effect is soundly identified in a study or experiment.
  Land tenure                                      Land tenure defines the property and use rights of an individual or group with respect to land.
  Longitudinal survey                               A panel or longitudinal survey is a survey in which the same survey units (households, holdings, individuals) are re-visited for at least one round after the baseline survey round.
  Measurement error                                 Deviation of a measured value of a parameter from its true value.
  Multi-topic household survey                     Sample survey with the household as its main unit of analysis and that studies multiple issues affecting the household, such as education, employment, poverty, migration, among others.
  National Statistical Office (NSO)                Government agency in charge of producing official statistics.
  Nonresponse                                       In surveys, nonresponse refers to selected respondents altogether failing to participate in the survey (unit nonresponse) or failing to respond to certain questions of the survey (item nonresponse).
  Non-sampling error                               Survey error not due to sampling, such as response errors, when survey respondents misreport on survey questions for example because survey questions are poorly framed, or errors resulting from nonresponse.
  Panel survey                                      A panel or longitudinal survey is a survey in which the same survey units (households, holdings, individuals) are re-visited for at least one round after the baseline survey round.
  Paper Assisted Personal interviewing (PAPI)      Survey interview mode whereby the enumerator uses pen and paper to fill the questionnaire.
  Parcel                                            A parcel is a piece of land of one land tenure type entirely surrounded by other land, water, road, forest or other features not forming part of the holding, or forming part of the holding under a different land tenure type. A parcel may comprise one or more plots.
  Pastoralism                                      Livestock production system involving the grazing of livestock herds on rangelands and large pastures typically practiced by nomadic people who move with their herds.
  Permanent crops                                  Crops with a growing cycle of more than one year (FAO, WCA 2020), and which do not need to be replanted after one growing cycle. Also referred to as *perennial crops*.
  Plot                                              A plot is defined as a continuous piece of land on which a specific crop or a mixture of crops is grown, or which is fallow or waiting to be planted.
  Plot manager                                     The manager of an agricultural plot is typically the main decision maker regarding crops planted, inputs applied, and output harvested.
  Post-harvest questionnaire                        Questionnaire administered during the post-harvest visit of the survey, that is, a survey visit taking place after the farm's main harvest of temporary/seasonal crops has been completed.
  Post-planting questionnaire                       Questionnaire administered during the post-planting visit of the survey, that is a survey visit taking place after the farm has completed the planting period of its main temporary/seasonal crops.
  Productivity                                      In this volume, productivity refers to agricultural productivity, whether yield (output per area of land), labor productivity (output per unit of labor or per worker), or total factor productivity, taking into account all inputs and outputs.
  Proxy response                                   In proxy response, an individual responds on behalf another individual, rather than all individuals responding directly for themselves.
  Randomized controlled trial                      Scientific experiment to test the causal effect of a treatment or an intervention while controlling for confounding factors through experimental design.
  Recall                                           Recall refers to the process of respondents self-reporting of past events of interest.
  Recall period                                    Length of the period between the interview and an event the respondent is requested to recall.
  Reference period                                 The period of reference for a survey question, for example, the reference agricultural season or the last 7 days.
  Representativeness                                A sample is representative if it accurately reflects the study population of interest with respect to a set of predefined characteristics.
  Research design                                  Methods, techniques, and strategies chosen to answer a given research question.
  Root crops                                        Root crops or root vegetables are those crops whose roots are meant for consumption, such as cassava or onions.
  Sample survey                                    Survey based on a sample of the entire population of interest, rather than full enumeration, usually designed to be representative of the population of interest.
  Sampling                                         Selecting a predetermined number of units from a population of interest, such as farms or households.
  Sampling error                                   Deviation of sample means from true population means leading to reduced representativeness of the sample.
  Sampling frame                                    A list of units, such as farms, from which a survey sample is drawn.
  Sex-disaggregated data                           Data that allows distinguishing between women and men at the level of the individual.
  Skip sequences/patterns                          In survey questionnaires, a skip pattern routes the respondent to a specific question based on his or her answer to a previous question.
  Smallholder                                       A smallholder or smallholder farmer is a person who owns and/or operates a small-scale agricultural holding, whether defined by land area, production volume, production technology, or other factors.
  Social desirability bias                          Social desirability bias refers to a response bias whereby survey respondents answer survey questions in a way they perceive as pleasing the interviewer.
  Survey design                                    Methods and techniques for developing and implementing a survey.
  Survey experiment                                Scientific experiment to test the impact of survey design on measurement through surveys.
  Survey methodology                               The study of survey methods.
  Survey respondent                                Individual who respondents to survey questions.
  Temporary crops                                  Crops with at least one growing cycle (planting and harvesting) per agricultural year, often once per reference agricultural season.
  Total survey error                                The sum of all errors from design, implementation, data processing and analysis of surveys.
  Tropical livestock units                         A standardized unit for measuring the stock of live animals independent of their breed or size.
  Unit of analysis                                 The unit of analysis or unit of observation is the unit of interest of a study or survey, such as farms, individuals, households, or enterprises. The unit of analysis may vary in one survey or study.
  Welfare                                           Measure of material wellbeing.

[^1]: For a deeper discussion of the evolution of methods and measurement in agricultural economics, see Fox (1986) and Herberich et al. (2009).

[^2]: The gold standard approach of individual, self-respondent interviews for the measurement of asset ownership and control in household surveys has been recently researched and supported by the United Nations Statistical Commission through the United Nations Evidence for Gender Equality (EDGE) Initiative. The EDGE Initiative led to the publication of the United Nations Guidelines for Producing Statistics on Asset Ownership from a Gender Perspective (UNSD, 2019).

[^3]: For more detailed guidance on data collection for monitoring SDGs 5.a.1 and 1.4.2, on land tenure, refer to the guidance document developed by the custodian agencies (FAO, The World Bank, and UN Habitat, 2019); available here: <http://documents.worldbank.org/curated/en/145891539095619258/pdf/Measuring-Individuals-Rights-to-Land-An-Integrated-Approach-to-Data-Collection-for-SDG-Indicators-1-4-2-and-5-a-1.pdf>

[^4]: Standard GPS devices have reported position accuracy of approximately ten meters depending on the model's satellite calibration algorithm (http://www8.garmin.com/aboutGPS/). GPS receivers using WAAS (Wide Area Augmentation System) can have accuracy of three meters by correcting for atmospheric conditions.

[^5]: In addition to land use information, Donaldson and Storeygard (2016) note remote sensing data sources available to produce data related to mineral deposits, elevation, terrain, and land cover, as well as airborne pollution, fish abundance and electricity use.

[^6]: Schøning et al. (2005) find a statistically significant difference for plots under 0.5 hectares but not for plots equal to or greater than 0.5 hectares. Keita and Carfagna (2009) separate their sample into five clusters based on plot size. They find a statistically significant difference for the clusters with the lowest land size but not for the clusters with larger plots. However, they do not specify the plot size range for each cluster.

[^7]: For guidance on the collection of data for labor more broadly, see the LSMS "Guidebook on Labor: Work and Employment in Multi-Topic Household Surveys" (forthcoming).

[^8]: Sample size of the 2015-16 Annual Agricultural Survey extracted from the CSA's Report on Area and Production of Major Crops, available [here](http://www.csa.gov.et/survey-report/category/347-eth-agss-2016). Sample size for the Ethiopia Socioeconomic Survey extracted from the World Bank's Microdata Catalog [here](https://microdata.worldbank.org/index.php/catalog/2783).

[^9]: Tracking protocols for the LSMS-ISA surveys are available as part of the documentation released with the survey data. Visit the World Bank's Microdata Library (<https://microdata.worldbank.org/>) to find all of the LSMS-ISA surveys. The tracking forms and protocols (included in the enumerator's manual) for the Malawi Integrated Household Panel Survey, for example, are available here: <https://microdata.worldbank.org/index.php/catalog/2939/related-materials>

[^10]: West, B.T. and Blom, A.G., 2017. Explaining interviewer effects: A research synthesis. Journal of Survey Statistics and Methodology, 5(2), pp.175-211.

[^11]: Cannell, C. F., and Laurent. (1977). A summary of studies of interviewing methodology. Vital and Health Statistics: Series 2, Data Evaluation and Methods Research (No. 69. DHEW Publication No. (HRA), 77-1343). Washington, DC: U.S. Government Printing Office.

[^12]: Fowler, F. J. Jr., and Mangione, T. W. (1985). The value of interviewer training and supervision (Final report to the National Center for Health services Research). Boston, MA: Center for Survey Research.

[^13]: Alcser K., Clemens J., Holland L., Guyer H., Hu M. 2016. Interviewer recruitment, selection, and training. Cross-Cultural Survey Guidelines. University of Michigan.

[^14]: For guidance on the implementation of GPS for area measurement, see the LSMS guidebook on Land Area Measurement in Household Surveys (Carletto et al., 2016).

[^15]: An example of a GPS anonymization protocol employed by the DHS program can be found [here](https://dhsprogram.com/What-We-Do/GPS-Data-Collection.cfm).
